#!/usr/bin/env python
# encoding: utf-8

name = "seed"
shortDesc = ""
longDesc = """

"""
autoGenerated=True
entry(
    index = 0,
    label = "[H] + [H] <=> H2",
    degeneracy = 0.5,
    kinetics = Arrhenius(A=(5.45e+10,'cm^3/(mol*s)'), n=0, Ea=(6.276,'kJ/mol'), T0=(1,'K'), Tmin=(278,'K'), Tmax=(372,'K'), comment="""Matched reaction 56 H + H <=> H2 in R_Recombination/training
    This reaction matched rate rule [Root_1R->H_N-2R->S_2CHNO->H]
    family: R_Recombination"""),
    longDesc = 
"""
Matched reaction 56 H + H <=> H2 in R_Recombination/training
This reaction matched rate rule [Root_1R->H_N-2R->S_2CHNO->H]
family: R_Recombination
""",
)

entry(
    index = 1,
    label = "O2 + H2 <=> [H] + [O]O",
    degeneracy = 4.0,
    kinetics = Arrhenius(A=(2.9e+14,'cm^3/(mol*s)','*|/',5), n=0, Ea=(236.982,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(800,'K'), comment="""Matched reaction 305 H2 + O2 <=> HO2_r12 + H in H_Abstraction/training
    This reaction matched rate rule [H2;O2b]
    family: H_Abstraction"""),
    longDesc = 
"""
Matched reaction 305 H2 + O2 <=> HO2_r12 + H in H_Abstraction/training
This reaction matched rate rule [H2;O2b]
family: H_Abstraction
""",
)

entry(
    index = 2,
    label = "O2 + [H] <=> [O]O",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(8.79e+10,'cm^3/(mol*s)'), n=1, Ea=(1.8828,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(6000,'K'), comment="""Matched reaction 104 O2 + H <=> HO2-2 in R_Recombination/training
    This reaction matched rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_N-Sp-3R!H=2CCNNOO_2CNO->O_3R!H->O]
    family: R_Recombination"""),
    longDesc = 
"""
Matched reaction 104 O2 + H <=> HO2-2 in R_Recombination/training
This reaction matched rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_N-Sp-3R!H=2CCNNOO_2CNO->O_3R!H->O]
family: R_Recombination
""",
)

entry(
    index = 3,
    label = "[O]O + CO <=> [OH] + CO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.41e+07,'cm^3/(mol*s)'), n=0, Ea=(12.552,'kJ/mol'), T0=(1,'K'), Tmin=(250,'K'), Tmax=(2500,'K'), comment="""From training reaction 9 used for COm;O_rad/NonDe
    Exact match found for rate rule [COm;O_rad/NonDe]
    Euclidian distance = 0
    family: R_Addition_COm"""),
    longDesc = 
"""
From training reaction 9 used for COm;O_rad/NonDe
Exact match found for rate rule [COm;O_rad/NonDe]
Euclidian distance = 0
family: R_Addition_COm
""",
)

entry(
    index = 4,
    label = "[O] + [OH] <=> [O]O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(15.4803,'m^3/(mol*s)'), n=1.88017, Ea=(5.1666,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using template [O_rad;O_birad] for rate rule [O_pri_rad;O_birad]
    Euclidian distance = 1.0
    family: Birad_R_Recombination"""),
    longDesc = 
"""
Estimated using template [O_rad;O_birad] for rate rule [O_pri_rad;O_birad]
Euclidian distance = 1.0
family: Birad_R_Recombination
""",
)

entry(
    index = 5,
    label = "[O] + [H] <=> [OH]",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Matched reaction 4 H + O <=> HO in Birad_R_Recombination/training
    This reaction matched rate rule [H_rad;O_birad]
    family: Birad_R_Recombination"""),
    longDesc = 
"""
Matched reaction 4 H + O <=> HO in Birad_R_Recombination/training
This reaction matched rate rule [H_rad;O_birad]
family: Birad_R_Recombination
""",
)

entry(
    index = 6,
    label = "[O] + [O]O <=> O2 + [OH]",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3820.63,'m^3/(mol*s)'), n=0.685179, Ea=(22.1161,'kJ/mol'), T0=(1,'K'), comment="""Estimated using average of templates [X_H;O_atom_triplet] + [Orad_O_H;Y_rad_birad_trirad_quadrad] for rate rule [Orad_O_H;O_atom_triplet]
    Euclidian distance = 2.0
    family: H_Abstraction"""),
    longDesc = 
"""
Estimated using average of templates [X_H;O_atom_triplet] + [Orad_O_H;Y_rad_birad_trirad_quadrad] for rate rule [Orad_O_H;O_atom_triplet]
Euclidian distance = 2.0
family: H_Abstraction
""",
)

entry(
    index = 7,
    label = "[O] + H2 <=> [H] + [OH]",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(3.4e+08,'cm^3/(mol*s)'), n=1.5, Ea=(96.0228,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Matched reaction 285 H2 + O_rad <=> HO + H in H_Abstraction/training
    This reaction matched rate rule [OH_rad_H;H_rad]
    family: H_Abstraction"""),
    longDesc = 
"""
Matched reaction 285 H2 + O_rad <=> HO + H in H_Abstraction/training
This reaction matched rate rule [OH_rad_H;H_rad]
family: H_Abstraction
""",
)

entry(
    index = 8,
    label = "O2 + [OH] <=> O=O + [OH]",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(4e+07,'m^3/(mol*s)'), n=1.78837e-07, Ea=(94.3116,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.1368631905, Tref=1000.0, N=1, data_mean=0.0, correlation='Root_N-1R->H_N-1CNOS->N_1COS->O_Ext-1O-R_N-2R->C_N-3R!H->N_2OS->O',), comment="""Estimated from node Root_N-1R->H_N-1CNOS->N_1COS->O_Ext-1O-R_N-2R->C_N-3R!H->N_2OS->O
    Multiplied by reaction path degeneracy 2.0
    Ea raised from 94.3 to 94.3 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated from node Root_N-1R->H_N-1CNOS->N_1COS->O_Ext-1O-R_N-2R->C_N-3R!H->N_2OS->O
Multiplied by reaction path degeneracy 2.0
Ea raised from 94.3 to 94.3 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 9,
    label = "[O] + [O]O <=> O=O + [OH]",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(15.4803,'m^3/(mol*s)'), n=1.88017, Ea=(5.1666,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""From training reaction 3 used for O_rad/NonDe;O_birad
    Exact match found for rate rule [O_rad/NonDe;O_birad]
    Euclidian distance = 0
    family: Birad_R_Recombination"""),
    longDesc = 
"""
From training reaction 3 used for O_rad/NonDe;O_birad
Exact match found for rate rule [O_rad/NonDe;O_birad]
Euclidian distance = 0
family: Birad_R_Recombination
""",
)

entry(
    index = 10,
    label = "O=O => O2",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(4.5e+10,'s^-1'), n=0, Ea=(397,'cal/mol'), T0=(1,'K'), comment="""Matched reaction 0 O2(S) => O2(T) in Singlet_Val6_to_triplet/training
    This reaction matched rate rule [O2]
    family: Singlet_Val6_to_triplet"""),
    longDesc = 
"""
Matched reaction 0 O2(S) => O2(T) in Singlet_Val6_to_triplet/training
This reaction matched rate rule [O2]
family: Singlet_Val6_to_triplet
""",
)

entry(
    index = 11,
    label = "[OH] + H2 <=> [H] + O",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(1.82e+09,'cm^3/(mol*s)'), n=1.21, Ea=(83.9729,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(2400,'K'), comment="""Matched reaction 311 H2 + OH <=> H2O_p + H_p in H_Abstraction/training
    This reaction matched rate rule [H2;O_pri_rad]
    family: H_Abstraction"""),
    longDesc = 
"""
Matched reaction 311 H2 + OH <=> H2O_p + H_p in H_Abstraction/training
This reaction matched rate rule [H2;O_pri_rad]
family: H_Abstraction
""",
)

entry(
    index = 12,
    label = "[H] + [OH] <=> O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.62e+14,'cm^3/(mol*s)'), n=0, Ea=(0.6276,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2100,'K'), comment="""Matched reaction 64 H + OH <=> H2O in R_Recombination/training
    This reaction matched rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_2CNO->O]
    family: R_Recombination"""),
    longDesc = 
"""
Matched reaction 64 H + OH <=> H2O in R_Recombination/training
This reaction matched rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_2CNO->O]
family: R_Recombination
""",
)

entry(
    index = 13,
    label = "O2 + O <=> [OH] + [O]O",
    degeneracy = 4.0,
    kinetics = Arrhenius(A=(9.3e+12,'cm^3/(mol*s)'), n=0, Ea=(310.118,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1000,'K'), comment="""Matched reaction 378 H2O + O2 <=> HO2_r12 + OH_p23 in H_Abstraction/training
    This reaction matched rate rule [Orad_O_H;O_pri_rad]
    family: H_Abstraction"""),
    longDesc = 
"""
Matched reaction 378 H2O + O2 <=> HO2_r12 + OH_p23 in H_Abstraction/training
This reaction matched rate rule [Orad_O_H;O_pri_rad]
family: H_Abstraction
""",
)

entry(
    index = 14,
    label = "[O] + O <=> [OH] + [OH]",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(5.26e+09,'cm^3/(mol*s)'), n=1.2, Ea=(74.6007,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(1000,'K'), comment="""Matched reaction 379 H2O + O_rad <=> HO + OH_p23 in H_Abstraction/training
    This reaction matched rate rule [OH_rad_H;O_pri_rad]
    family: H_Abstraction"""),
    longDesc = 
"""
Matched reaction 379 H2O + O_rad <=> HO + OH_p23 in H_Abstraction/training
This reaction matched rate rule [OH_rad_H;O_pri_rad]
family: H_Abstraction
""",
)

entry(
    index = 15,
    label = "[H] + OO <=> [O]O + H2",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(1.1185,'m^3/(mol*s)'), n=1.66084, Ea=(28.0205,'kJ/mol'), T0=(1,'K'), comment="""Estimated using average of templates [O/H/NonDeO;H_rad] + [H2O2;Y_rad] for rate rule [H2O2;H_rad]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: H_Abstraction"""),
    longDesc = 
"""
Estimated using average of templates [O/H/NonDeO;H_rad] + [H2O2;Y_rad] for rate rule [H2O2;H_rad]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: H_Abstraction
""",
)

entry(
    index = 16,
    label = "[H] + [O]O <=> OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5250.69,'m^3/(mol*s)'), n=1.27262, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.1368631905, Tref=1000.0, N=1, data_mean=0.0, correlation='Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_N-Sp-3R!H=2CCNNOO_2CNO->O_3R!H->O',), comment="""Estimated from node Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_N-Sp-3R!H=2CCNNOO_2CNO->O_3R!H->O"""),
    longDesc = 
"""
Estimated from node Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_N-Sp-3R!H=2CCNNOO_2CNO->O_3R!H->O
""",
)

entry(
    index = 17,
    label = "[O]O + [O]O <=> O2 + OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.75e+10,'cm^3/(mol*s)'), n=0, Ea=(-13.7026,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Matched reaction 404 HO2_r3 + HO2_r12 <=> H2O2 + O2 in H_Abstraction/training
    This reaction matched rate rule [Orad_O_H;O_rad/NonDeO]
    family: H_Abstraction"""),
    longDesc = 
"""
Matched reaction 404 HO2_r3 + HO2_r12 <=> H2O2 + O2 in H_Abstraction/training
This reaction matched rate rule [Orad_O_H;O_rad/NonDeO]
family: H_Abstraction
""",
)

entry(
    index = 18,
    label = "[O] + OO <=> [OH] + [O]O",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(1.74e+13,'cm^3/(mol*s)'), n=0, Ea=(19.874,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [O/H/NonDeO;O_atom_triplet] for rate rule [H2O2;O_atom_triplet]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: H_Abstraction"""),
    longDesc = 
"""
Estimated using template [O/H/NonDeO;O_atom_triplet] for rate rule [H2O2;O_atom_triplet]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: H_Abstraction
""",
)

entry(
    index = 19,
    label = "[OH] + [OH] <=> OO",
    degeneracy = 0.5,
    kinetics = Arrhenius(A=(7.85e+12,'cm^3/(mol*s)','+|-',6.02e+12), n=(0,'','+|-',0.5), Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(400,'K'), comment="""Matched reaction 96 OH + OH <=> H2O2 in R_Recombination/training
    This reaction matched rate rule [Root_N-1R->H_N-1CNOS->N_1COS->O_N-2R->C]
    family: R_Recombination"""),
    longDesc = 
"""
Matched reaction 96 OH + OH <=> H2O2 in R_Recombination/training
This reaction matched rate rule [Root_N-1R->H_N-1CNOS->N_1COS->O_N-2R->C]
family: R_Recombination
""",
)

entry(
    index = 20,
    label = "[OH] + OO <=> [O]O + O",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(0.4995,'m^3/(mol*s)'), n=1.9275, Ea=(26.4644,'kJ/mol'), T0=(1,'K'), comment="""Estimated using average of templates [O/H/NonDeO;O_pri_rad] + [H2O2;O_rad] for rate rule [H2O2;O_pri_rad]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: H_Abstraction"""),
    longDesc = 
"""
Estimated using average of templates [O/H/NonDeO;O_pri_rad] + [H2O2;O_rad] for rate rule [H2O2;O_pri_rad]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: H_Abstraction
""",
)

entry(
    index = 21,
    label = "[H] + [CH]=O <=> H2 + CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.03e+13,'cm^3/(mol*s)','*|/',2), n=0, Ea=(0,'cal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), comment="""Matched reaction 0 HCO + H <=> CO + H2 in CO_Disproportionation/training
    This reaction matched rate rule [Root_N-4R->N_4BrCClFHIOPSSi->H]
    family: CO_Disproportionation"""),
    longDesc = 
"""
Matched reaction 0 HCO + H <=> CO + H2 in CO_Disproportionation/training
This reaction matched rate rule [Root_N-4R->N_4BrCClFHIOPSSi->H]
family: CO_Disproportionation
""",
)

entry(
    index = 22,
    label = "[H] + CO <=> [CH]=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.18e+11,'cm^3/(mol*s)'), n=0, Ea=(11.3805,'kJ/mol'), T0=(1,'K'), Tmin=(345,'K'), Tmax=(449,'K'), comment="""Matched reaction 4 H + CO <=> CHO in R_Addition_COm/training
    This reaction matched rate rule [COm;H_rad]
    family: R_Addition_COm"""),
    longDesc = 
"""
Matched reaction 4 H + CO <=> CHO in R_Addition_COm/training
This reaction matched rate rule [COm;H_rad]
family: R_Addition_COm
""",
)

entry(
    index = 23,
    label = "O2 + [CH]=O <=> [O]O + CO",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(5.12e+13,'cm^3/(mol*s)'), n=0, Ea=(1690,'cal/mol'), T0=(1,'K'), comment="""Matched reaction 2 HCO + O2 <=> CO + HO2 in CO_Disproportionation/training
    This reaction matched rate rule [Root_N-4R->N_N-4BrCClFHIOPSSi->H_Ext-4CO-R_N-5R!H->C_5BrClFINOPSSi->O_N-4CO->C]
    family: CO_Disproportionation"""),
    longDesc = 
"""
Matched reaction 2 HCO + O2 <=> CO + HO2 in CO_Disproportionation/training
This reaction matched rate rule [Root_N-4R->N_N-4BrCClFHIOPSSi->H_Ext-4CO-R_N-5R!H->C_5BrClFINOPSSi->O_N-4CO->C]
family: CO_Disproportionation
""",
)

entry(
    index = 24,
    label = "[O] + [CH]=O <=> [OH] + CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.01e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K'), comment="""Matched reaction 1 HCO + O <=> CO + OH in CO_Disproportionation/training
    This reaction matched rate rule [Root_N-4R->N_N-4BrCClFHIOPSSi->H_N-4CO->C]
    family: CO_Disproportionation"""),
    longDesc = 
"""
Matched reaction 1 HCO + O <=> CO + OH in CO_Disproportionation/training
This reaction matched rate rule [Root_N-4R->N_N-4BrCClFHIOPSSi->H_N-4CO->C]
family: CO_Disproportionation
""",
)

entry(
    index = 25,
    label = "[OH] + [CH]=O <=> O + CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.01e+07,'m^3/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.13686319048999, Tref=1000.0, N=1, data_mean=0.0, correlation='Root_N-4R->N_N-4BrCClFHIOPSSi->H_N-4CO->C',), comment="""Estimated from node Root_N-4R->N_N-4BrCClFHIOPSSi->H_N-4CO->C"""),
    longDesc = 
"""
Estimated from node Root_N-4R->N_N-4BrCClFHIOPSSi->H_N-4CO->C
""",
)

entry(
    index = 26,
    label = "[O]O + [CH]=O <=> OO + CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.12e+07,'m^3/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.13686319048999, Tref=1000.0, N=1, data_mean=0.0, correlation='Root_N-4R->N_N-4BrCClFHIOPSSi->H_Ext-4CO-R_N-5R!H->C_5BrClFINOPSSi->O_N-4CO->C',), comment="""Estimated from node Root_N-4R->N_N-4BrCClFHIOPSSi->H_Ext-4CO-R_N-5R!H->C_5BrClFINOPSSi->O_N-4CO->C"""),
    longDesc = 
"""
Estimated from node Root_N-4R->N_N-4BrCClFHIOPSSi->H_Ext-4CO-R_N-5R!H->C_5BrClFINOPSSi->O_N-4CO->C
""",
)

entry(
    index = 27,
    label = "[OH] + CO <=> O=[C]O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.41e+07,'cm^3/(mol*s)'), n=0, Ea=(12.552,'kJ/mol'), T0=(1,'K'), Tmin=(250,'K'), Tmax=(2500,'K'), comment="""Estimated using template [COm;O_rad] for rate rule [COm;O_pri_rad]
    Euclidian distance = 1.0
    family: R_Addition_COm"""),
    longDesc = 
"""
Estimated using template [COm;O_rad] for rate rule [COm;O_pri_rad]
Euclidian distance = 1.0
family: R_Addition_COm
""",
)

entry(
    index = 28,
    label = "[H] + CO2 <=> O=[C]O",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(2.37e+08,'cm^3/(mol*s)'), n=1.63, Ea=(30.7064,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1700,'K'), comment="""Estimated using template [Od_R;HJ] for rate rule [Od_Cdd-O2d;HJ]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 2.0
    family: R_Addition_MultipleBond"""),
    longDesc = 
"""
Estimated using template [Od_R;HJ] for rate rule [Od_Cdd-O2d;HJ]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: R_Addition_MultipleBond
""",
)

entry(
    index = 29,
    label = "O2 + O=[C]O <=> [O]O + CO2",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(1.14418e+07,'m^3/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.13686319048999, Tref=1000.0, N=1, data_mean=0.0, correlation='Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C_Ext-4CNOS-R_N-Sp-5R!H=4CCNNOOSS_N-4CNOS->C_N-5R!H-u0',), comment="""Estimated from node Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C_Ext-4CNOS-R_N-Sp-5R!H=4CCNNOOSS_N-4CNOS->C_N-5R!H-u0
    Multiplied by reaction path degeneracy 2.0"""),
    longDesc = 
"""
Estimated from node Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C_Ext-4CNOS-R_N-Sp-5R!H=4CCNNOOSS_N-4CNOS->C_N-5R!H-u0
Multiplied by reaction path degeneracy 2.0
""",
)

entry(
    index = 30,
    label = "[H] + O=[C]O <=> H2 + CO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2e+07,'m^3/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(295,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.13686319048999, Tref=1000.0, N=1, data_mean=0.0, correlation='Root_4R->H_Sp-2R!H-1R!H_2R!H-u1_1R!H->O_2R!H->C',), comment="""Estimated from node Root_4R->H_Sp-2R!H-1R!H_2R!H-u1_1R!H->O_2R!H->C"""),
    longDesc = 
"""
Estimated from node Root_4R->H_Sp-2R!H-1R!H_2R!H-u1_1R!H->O_2R!H->C
""",
)

entry(
    index = 31,
    label = "[O]O + O=[C]O <=> OO + CO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.21e+07,'m^3/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.13686319048999, Tref=1000.0, N=1, data_mean=0.0, correlation='Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C_Ext-4CNOS-R_N-Sp-5R!H=4CCNNOOSS_N-4CNOS->C_5R!H-u0_N-5R!H->C',), comment="""Estimated from node Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C_Ext-4CNOS-R_N-Sp-5R!H=4CCNNOOSS_N-4CNOS->C_5R!H-u0_N-5R!H->C"""),
    longDesc = 
"""
Estimated from node Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C_Ext-4CNOS-R_N-Sp-5R!H=4CCNNOOSS_N-4CNOS->C_5R!H-u0_N-5R!H->C
""",
)

entry(
    index = 32,
    label = "[OH] + O=[C]O <=> O + CO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.41e+07,'m^3/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.13686319048999, Tref=1000.0, N=1, data_mean=0.0, correlation='Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C_N-4CNOS->C',), comment="""Estimated from node Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C_N-4CNOS->C"""),
    longDesc = 
"""
Estimated from node Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C_N-4CNOS->C
""",
)

entry(
    index = 33,
    label = "[O] + O=[C]O <=> [OH] + CO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.04e+07,'m^3/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.13686319048999, Tref=1000.0, N=1, data_mean=0.0, correlation='Root_N-4R->H_N-4CNOS-u1_1R!H->O_N-4CNOS->C_2R!H->C',), comment="""Estimated from node Root_N-4R->H_N-4CNOS-u1_1R!H->O_N-4CNOS->C_2R!H->C"""),
    longDesc = 
"""
Estimated from node Root_N-4R->H_N-4CNOS-u1_1R!H->O_N-4CNOS->C_2R!H->C
""",
)

entry(
    index = 34,
    label = "[O]O + CO <=> [O]OC=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.0591985,'m^3/(mol*s)'), n=2.3675, Ea=(305.306,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [CO;R_H]
    Euclidian distance = 0
    family: 1,2_Insertion_CO"""),
    longDesc = 
"""
Estimated using an average for rate rule [CO;R_H]
Euclidian distance = 0
family: 1,2_Insertion_CO
""",
)

entry(
    index = 35,
    label = "O2 + [CH]=O <=> [O]OC=O",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(7e+12,'cm^3/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), comment="""Matched reaction 119 O2 + CHO <=> CHO3 in R_Recombination/training
    This reaction matched rate rule [Root_N-1R->H_N-1CNOS->N_1COS->O_Ext-1O-R_Ext-2R-R_N-Sp-4R!H-2R_4R!H->O]
    family: R_Recombination"""),
    longDesc = 
"""
Matched reaction 119 O2 + CHO <=> CHO3 in R_Recombination/training
This reaction matched rate rule [Root_N-1R->H_N-1CNOS->N_1COS->O_Ext-1O-R_Ext-2R-R_N-Sp-4R!H-2R_4R!H->O]
family: R_Recombination
""",
)

entry(
    index = 36,
    label = "[O]OC=O <=> [OH] + CO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.83109e+08,'s^-1'), n=1.32333, Ea=(164.794,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [R3H_SS_O;O_rad_out;XH_out] for rate rule [R3H_SS_O;O_rad_out;CO_H_out]
    Euclidian distance = 1.0
    family: intra_H_migration"""),
    longDesc = 
"""
Estimated using template [R3H_SS_O;O_rad_out;XH_out] for rate rule [R3H_SS_O;O_rad_out;CO_H_out]
Euclidian distance = 1.0
family: intra_H_migration
""",
)

entry(
    index = 37,
    label = "O + CO <=> O=CO",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(0.254,'cm^3/(mol*s)'), n=3.7, Ea=(223.258,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Estimated using an average for rate rule [CO;RO_H]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: 1,2_Insertion_CO"""),
    longDesc = 
"""
Estimated using an average for rate rule [CO;RO_H]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: 1,2_Insertion_CO
""",
)

entry(
    index = 38,
    label = "[OH] + [CH]=O <=> O=CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7.7e+07,'m^3/(mol*s)'), n=4.95181e-08, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.1368631905, Tref=1000.0, N=1, data_mean=0.0, correlation='Root_N-1R->H_N-1CNOS->N_1COS->O_2R->C_Ext-2C-R',), comment="""Estimated from node Root_N-1R->H_N-1CNOS->N_1COS->O_2R->C_Ext-2C-R"""),
    longDesc = 
"""
Estimated from node Root_N-1R->H_N-1CNOS->N_1COS->O_2R->C_Ext-2C-R
""",
)

entry(
    index = 39,
    label = "[H] + O=CO <=> H2 + O=[C]O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(130000,'cm^3/(mol*s)'), n=2.58, Ea=(5.1003,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [CO/H/NonDe;H_rad]
    Euclidian distance = 0
    family: H_Abstraction"""),
    longDesc = 
"""
Estimated using an average for rate rule [CO/H/NonDe;H_rad]
Euclidian distance = 0
family: H_Abstraction
""",
)

entry(
    index = 40,
    label = "[H] + O=[C]O <=> O=CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.10287e+13,'m^3/(mol*s)'), n=-2.74437, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.1368631905, Tref=1000.0, N=1, data_mean=0.0, correlation='Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO_3R!H->O',), comment="""Estimated from node Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO_3R!H->O"""),
    longDesc = 
"""
Estimated from node Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO_3R!H->O
""",
)

entry(
    index = 41,
    label = "[O]O + O=[C]O <=> O2 + O=CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.027594,'m^3/(mol*s)'), n=2.25396, Ea=(154.797,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [X_H;CO_rad/NonDe] for rate rule [Orad_O_H;CO_rad/NonDe]
    Euclidian distance = 2.0
    family: H_Abstraction"""),
    longDesc = 
"""
Estimated using template [X_H;CO_rad/NonDe] for rate rule [Orad_O_H;CO_rad/NonDe]
Euclidian distance = 2.0
family: H_Abstraction
""",
)

entry(
    index = 42,
    label = "[O] + O=CO <=> [OH] + O=[C]O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.8e+12,'cm^3/(mol*s)'), n=0, Ea=(7.56467,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [CO/H/NonDe;O_atom_triplet]
    Euclidian distance = 0
    family: H_Abstraction"""),
    longDesc = 
"""
Estimated using an average for rate rule [CO/H/NonDe;O_atom_triplet]
Euclidian distance = 0
family: H_Abstraction
""",
)

entry(
    index = 43,
    label = "[OH] + O=CO <=> O + O=[C]O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.8e+12,'cm^3/(mol*s)'), n=0, Ea=(-2.96646,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [CO/H/NonDe;O_pri_rad]
    Euclidian distance = 0
    family: H_Abstraction"""),
    longDesc = 
"""
Estimated using an average for rate rule [CO/H/NonDe;O_pri_rad]
Euclidian distance = 0
family: H_Abstraction
""",
)

entry(
    index = 44,
    label = "OO + O=[C]O <=> [O]O + O=CO",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(8.66e-06,'cm^3/(mol*s)'), n=5.09, Ea=(164.32,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Estimated using an average for rate rule [H2O2;CO_rad/NonDe]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: H_Abstraction"""),
    longDesc = 
"""
Estimated using an average for rate rule [H2O2;CO_rad/NonDe]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: H_Abstraction
""",
)

entry(
    index = 45,
    label = "[CH]=O + O=[C]O <=> CO + O=CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+07,'m^3/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.13686319048999, Tref=1000.0, N=1, data_mean=0.0, correlation='Root_N-4R->N_N-4BrCClFHIOPSSi->H_Ext-4CO-R_N-5R!H->C_5BrClFINOPSSi->O_4CO->C_Sp-5O-4C',), comment="""Estimated from node Root_N-4R->N_N-4BrCClFHIOPSSi->H_Ext-4CO-R_N-5R!H->C_5BrClFINOPSSi->O_4CO->C_Sp-5O-4C"""),
    longDesc = 
"""
Estimated from node Root_N-4R->N_N-4BrCClFHIOPSSi->H_Ext-4CO-R_N-5R!H->C_5BrClFINOPSSi->O_4CO->C_Sp-5O-4C
""",
)

entry(
    index = 46,
    label = "O=[C]O + O=[C]O <=> CO2 + O=CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.81e+08,'m^3/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.13686319048999, Tref=1000.0, N=1, data_mean=0.0, correlation='Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C_Ext-4CNOS-R_Sp-5R!H=4CCNNOOSS_N-5R!H->C',), comment="""Estimated from node Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C_Ext-4CNOS-R_Sp-5R!H=4CCNNOOSS_N-5R!H->C"""),
    longDesc = 
"""
Estimated from node Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C_Ext-4CNOS-R_Sp-5R!H=4CCNNOOSS_N-5R!H->C
""",
)

entry(
    index = 47,
    label = "H2 + CO2 <=> O=CO",
    degeneracy = 4.0,
    kinetics = Arrhenius(A=(1.51e+09,'cm^3/(mol*s)'), n=1.23, Ea=(309.198,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Matched reaction 0 H2 + CO2 <=> CH2O2 in 1,3_Insertion_CO2/training
    This reaction matched rate rule [Root_N-5CbCdCsHN->Cs_4CbCdCsHN->H_N-5CbCdHN->Cd]
    family: 1,3_Insertion_CO2"""),
    longDesc = 
"""
Matched reaction 0 H2 + CO2 <=> CH2O2 in 1,3_Insertion_CO2/training
This reaction matched rate rule [Root_N-5CbCdCsHN->Cs_4CbCdCsHN->H_N-5CbCdHN->Cd]
family: 1,3_Insertion_CO2
""",
)

entry(
    index = 48,
    label = "[O] + [CH]=O <=> [O]C=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1667.73,'m^3/(mol*s)'), n=1.126, Ea=(-8.29601,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using template [Y_rad;O_birad] for rate rule [CO_pri_rad;O_birad]
    Euclidian distance = 2.0
    family: Birad_R_Recombination"""),
    longDesc = 
"""
Estimated using template [Y_rad;O_birad] for rate rule [CO_pri_rad;O_birad]
Euclidian distance = 2.0
family: Birad_R_Recombination
""",
)

entry(
    index = 49,
    label = "[O]C=O <=> O=[C]O",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(4.3e+14,'s^-1','+|-',2), n=-0.27, Ea=(113.972,'kJ/mol'), T0=(1,'K'), Tmin=(700,'K'), Tmax=(1800,'K'), comment="""Estimated using template [R2H_S;O_rad_out;XH_out] for rate rule [R2H_S;O_rad_out;CO_H_out]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: intra_H_migration"""),
    longDesc = 
"""
Estimated using template [R2H_S;O_rad_out;XH_out] for rate rule [R2H_S;O_rad_out;CO_H_out]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: intra_H_migration
""",
)

entry(
    index = 50,
    label = "[O] + [O]C=O <=> [O]OC=O",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(30.9605,'m^3/(mol*s)'), n=1.88017, Ea=(5.1666,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using template [O_sec_rad;O_birad] for rate rule [O_rad/OneDe;O_birad]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Birad_R_Recombination"""),
    longDesc = 
"""
Estimated using template [O_sec_rad;O_birad] for rate rule [O_rad/OneDe;O_birad]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Birad_R_Recombination
""",
)

entry(
    index = 51,
    label = "[H] + [O]C=O <=> O=CO",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(5.6103e+06,'m^3/(mol*s)'), n=0.314888, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.1368631905, Tref=1000.0, N=1, data_mean=0.0, correlation='Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_N-Sp-3R!H=2CCNNOO_2CNO->O_N-3R!H->O',), comment="""Estimated from node Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_N-Sp-3R!H=2CCNNOO_2CNO->O_N-3R!H->O
    Multiplied by reaction path degeneracy 2.0"""),
    longDesc = 
"""
Estimated from node Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_N-Sp-3R!H=2CCNNOO_2CNO->O_N-3R!H->O
Multiplied by reaction path degeneracy 2.0
""",
)

entry(
    index = 52,
    label = "[CH]=O + [O]C=O <=> CO + O=CO",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(1.806e+08,'m^3/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.13686319048999, Tref=1000.0, N=1, data_mean=0.0, correlation='Root_N-4R->N_N-4BrCClFHIOPSSi->H_Ext-4CO-R_5R!H->C_Sp-5C-4CO_N-4CO->C',), comment="""Estimated from node Root_N-4R->N_N-4BrCClFHIOPSSi->H_Ext-4CO-R_5R!H->C_Sp-5C-4CO_N-4CO->C
    Multiplied by reaction path degeneracy 2.0"""),
    longDesc = 
"""
Estimated from node Root_N-4R->N_N-4BrCClFHIOPSSi->H_Ext-4CO-R_5R!H->C_Sp-5C-4CO_N-4CO->C
Multiplied by reaction path degeneracy 2.0
""",
)

entry(
    index = 53,
    label = "[O]O + [O]C=O <=> O2 + O=CO",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(0.00631933,'m^3/(mol*s)'), n=2.30237, Ea=(35.8501,'kJ/mol'), T0=(1,'K'), comment="""Estimated using average of templates [X_H;O_rad/OneDeC] + [Orad_O_H;O_sec_rad] for rate rule [Orad_O_H;O_rad/OneDeC]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 2.0
    family: H_Abstraction"""),
    longDesc = 
"""
Estimated using average of templates [X_H;O_rad/OneDeC] + [Orad_O_H;O_sec_rad] for rate rule [Orad_O_H;O_rad/OneDeC]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: H_Abstraction
""",
)

entry(
    index = 54,
    label = "[H] + O=CO <=> H2 + [O]C=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.4e+08,'cm^3/(mol*s)'), n=1.5, Ea=(27.6981,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""From training reaction 690 used for O/H/OneDeC;H_rad
    Exact match found for rate rule [O/H/OneDeC;H_rad]
    Euclidian distance = 0
    family: H_Abstraction"""),
    longDesc = 
"""
From training reaction 690 used for O/H/OneDeC;H_rad
Exact match found for rate rule [O/H/OneDeC;H_rad]
Euclidian distance = 0
family: H_Abstraction
""",
)

entry(
    index = 55,
    label = "OO + [O]C=O <=> [O]O + O=CO",
    degeneracy = 4.0,
    kinetics = Arrhenius(A=(1.398e-07,'m^3/(mol*s)'), n=3.75, Ea=(81.7744,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [H2O2;O_rad/OneDeC]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 4.0
    family: H_Abstraction"""),
    longDesc = 
"""
Estimated using an average for rate rule [H2O2;O_rad/OneDeC]
Euclidian distance = 0
Multiplied by reaction path degeneracy 4.0
family: H_Abstraction
""",
)

entry(
    index = 56,
    label = "[OH] + O=CO <=> O + [O]C=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.2e+06,'cm^3/(mol*s)'), n=2, Ea=(-1.046,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""From training reaction 692 used for O/H/OneDeC;O_pri_rad
    Exact match found for rate rule [O/H/OneDeC;O_pri_rad]
    Euclidian distance = 0
    family: H_Abstraction"""),
    longDesc = 
"""
From training reaction 692 used for O/H/OneDeC;O_pri_rad
Exact match found for rate rule [O/H/OneDeC;O_pri_rad]
Euclidian distance = 0
family: H_Abstraction
""",
)

entry(
    index = 57,
    label = "[O] + O=CO <=> [OH] + [O]C=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.7e+08,'cm^3/(mol*s)'), n=1.5, Ea=(17.2799,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""From training reaction 691 used for O/H/OneDeC;O_atom_triplet
    Exact match found for rate rule [O/H/OneDeC;O_atom_triplet]
    Euclidian distance = 0
    family: H_Abstraction"""),
    longDesc = 
"""
From training reaction 691 used for O/H/OneDeC;O_atom_triplet
Exact match found for rate rule [O/H/OneDeC;O_atom_triplet]
Euclidian distance = 0
family: H_Abstraction
""",
)

entry(
    index = 58,
    label = "[O]C=O + O=CO <=> O=[C]O + O=CO",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(1968.45,'m^3/(mol*s)'), n=1.0625, Ea=(51.9747,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [CO/H/NonDe;O_sec_rad] for rate rule [CO/H/NonDe;O_rad/OneDeC]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 2.0
    family: H_Abstraction"""),
    longDesc = 
"""
Estimated using template [CO/H/NonDe;O_sec_rad] for rate rule [CO/H/NonDe;O_rad/OneDeC]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: H_Abstraction
""",
)

entry(
    index = 59,
    label = "[H] + CO2 <=> [O]C=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7699.21,'m^3/(mol*s)'), n=1.33054, Ea=(21.3479,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Cdd_Od;HJ] for rate rule [CO2;HJ]
    Euclidian distance = 1.0
    family: R_Addition_MultipleBond
    Ea raised from 17.5 to 21.3 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Cdd_Od;HJ] for rate rule [CO2;HJ]
Euclidian distance = 1.0
family: R_Addition_MultipleBond
Ea raised from 17.5 to 21.3 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 60,
    label = "O2 + [O]C=O <=> [O]O + CO2",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(18890.2,'m^3/(mol*s)'), n=0.508694, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-1.8021051701158732, var=30.01095873466917, Tref=1000.0, N=45, data_mean=0.0, correlation='Root_Ext-1R!H-R',), comment="""Estimated from node Root_Ext-1R!H-R
    Multiplied by reaction path degeneracy 2.0"""),
    longDesc = 
"""
Estimated from node Root_Ext-1R!H-R
Multiplied by reaction path degeneracy 2.0
""",
)

entry(
    index = 61,
    label = "[H] + [O]C=O <=> H2 + CO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(13564.2,'m^3/(mol*s)'), n=0.470009, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-2.1185860084328203, var=34.56885654617875, Tref=1000.0, N=33, data_mean=0.0, correlation='Root_Ext-1R!H-R_N-4R->O',), comment="""Estimated from node Root_Ext-1R!H-R_N-4R->O"""),
    longDesc = 
"""
Estimated from node Root_Ext-1R!H-R_N-4R->O
""",
)

entry(
    index = 62,
    label = "[O]O + [O]C=O <=> OO + CO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9445.08,'m^3/(mol*s)'), n=0.508694, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-1.8021051701158732, var=30.01095873466917, Tref=1000.0, N=45, data_mean=0.0, correlation='Root_Ext-1R!H-R',), comment="""Estimated from node Root_Ext-1R!H-R"""),
    longDesc = 
"""
Estimated from node Root_Ext-1R!H-R
""",
)

entry(
    index = 63,
    label = "[OH] + [O]C=O <=> O + CO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9445.08,'m^3/(mol*s)'), n=0.508694, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-1.8021051701158732, var=30.01095873466917, Tref=1000.0, N=45, data_mean=0.0, correlation='Root_Ext-1R!H-R',), comment="""Estimated from node Root_Ext-1R!H-R"""),
    longDesc = 
"""
Estimated from node Root_Ext-1R!H-R
""",
)

entry(
    index = 64,
    label = "[O] + [O]C=O <=> [OH] + CO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9445.08,'m^3/(mol*s)'), n=0.508694, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-1.8021051701158732, var=30.01095873466917, Tref=1000.0, N=45, data_mean=0.0, correlation='Root_Ext-1R!H-R',), comment="""Estimated from node Root_Ext-1R!H-R"""),
    longDesc = 
"""
Estimated from node Root_Ext-1R!H-R
""",
)

entry(
    index = 65,
    label = "O=[C]O + [O]C=O <=> CO2 + O=CO",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = Arrhenius(A=(13564.2,'m^3/(mol*s)'), n=0.470009, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-2.1185860084328203, var=34.56885654617875, Tref=1000.0, N=33, data_mean=0.0, correlation='Root_Ext-1R!H-R_N-4R->O',), comment="""Estimated from node Root_Ext-1R!H-R_N-4R->O"""),
    longDesc = 
"""
Estimated from node Root_Ext-1R!H-R_N-4R->O
""",
)

entry(
    index = 66,
    label = "O=[C]O + [O]C=O <=> CO2 + O=CO",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = Arrhenius(A=(3.62e+07,'m^3/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.13686319048999, Tref=1000.0, N=1, data_mean=0.0, correlation='Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C_Ext-4CNOS-R_N-Sp-5R!H=4CCNNOOSS_Ext-5R!H-R',), comment="""Estimated from node Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C_Ext-4CNOS-R_N-Sp-5R!H=4CCNNOOSS_Ext-5R!H-R
    Multiplied by reaction path degeneracy 2.0"""),
    longDesc = 
"""
Estimated from node Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C_Ext-4CNOS-R_N-Sp-5R!H=4CCNNOOSS_Ext-5R!H-R
Multiplied by reaction path degeneracy 2.0
""",
)

entry(
    index = 67,
    label = "[O]C=O + [O]C=O <=> CO2 + O=CO",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(18890.2,'m^3/(mol*s)'), n=0.508694, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-1.8021051701158732, var=30.01095873466917, Tref=1000.0, N=45, data_mean=0.0, correlation='Root_Ext-1R!H-R',), comment="""Estimated from node Root_Ext-1R!H-R
    Multiplied by reaction path degeneracy 2.0"""),
    longDesc = 
"""
Estimated from node Root_Ext-1R!H-R
Multiplied by reaction path degeneracy 2.0
""",
)

