#!/usr/bin/env python
# encoding: utf-8

name = "seed"
shortDesc = ""
longDesc = """

"""
autoGenerated=True
entry(
    index = 0,
    label = "[H] + [H] <=> H2",
    degeneracy = 0.5,
    kinetics = Arrhenius(A=(5.45e+10,'cm^3/(mol*s)'), n=0, Ea=(6.276,'kJ/mol'), T0=(1,'K'), Tmin=(278,'K'), Tmax=(372,'K'), comment="""Matched reaction 56 H + H <=> H2 in R_Recombination/training
    This reaction matched rate rule [Root_1R->H_N-2R->S_2CHNO->H]
    family: R_Recombination"""),
    longDesc = 
"""
Matched reaction 56 H + H <=> H2 in R_Recombination/training
This reaction matched rate rule [Root_1R->H_N-2R->S_2CHNO->H]
family: R_Recombination
""",
)

entry(
    index = 1,
    label = "O2 + H2 <=> [H] + [O]O",
    degeneracy = 4.0,
    kinetics = Arrhenius(A=(2.9e+14,'cm^3/(mol*s)','*|/',5), n=0, Ea=(236.982,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(800,'K'), comment="""Matched reaction 305 H2 + O2 <=> HO2_r12 + H in H_Abstraction/training
    This reaction matched rate rule [H2;O2b]
    family: H_Abstraction"""),
    longDesc = 
"""
Matched reaction 305 H2 + O2 <=> HO2_r12 + H in H_Abstraction/training
This reaction matched rate rule [H2;O2b]
family: H_Abstraction
""",
)

entry(
    index = 2,
    label = "O2 + [H] <=> [O]O",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(8.79e+10,'cm^3/(mol*s)'), n=1, Ea=(1.8828,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(6000,'K'), comment="""Matched reaction 104 O2 + H <=> HO2-2 in R_Recombination/training
    This reaction matched rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_N-Sp-3R!H=2CCNNOO_2CNO->O_3R!H->O]
    family: R_Recombination"""),
    longDesc = 
"""
Matched reaction 104 O2 + H <=> HO2-2 in R_Recombination/training
This reaction matched rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_N-Sp-3R!H=2CCNNOO_2CNO->O_3R!H->O]
family: R_Recombination
""",
)

